# Generated by Django 3.1.2 on 2020-12-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20201227_0343'),
        ('GnC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midyrcommentbox',
            name='appraisal',
        ),
        migrations.RemoveField(
            model_name='midyrcommentbox',
            name='user',
        ),
        migrations.CreateModel(
            name='EndYrCommentBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GnC.goals')),
            ],
        ),
    ]
