# Generated by Django 3.1.2 on 2021-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0003_goals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='goal_employees_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='goal_manager_comment',
            field=models.TextField(null=True),
        ),
    ]
