# Generated by Django 3.1.2 on 2021-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0004_auto_20210107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=100, null=True),
        ),
    ]
