# Generated by Django 3.1.2 on 2021-04-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0008_auto_20210407_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cascadedgoals',
            old_name='employee',
            new_name='emaployees',
        ),
    ]
