# Generated by Django 3.1.2 on 2021-04-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0009_auto_20210407_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='cascaded_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.cascadedgoals'),
        ),
    ]
