# Generated by Django 3.2.3 on 2021-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0010_goals_cascaded_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
