version: '3'

volumes:
  rabbitmqmain:
  rabbitmqdata:
  rabbitmqlogs:
  pgdata:


services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqmain:/etc/rabbitmq/
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlogs:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025

  denselightdjango: &denselightdjango
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: denselight_django_image
    container_name: denselight_django
    depends_on:
      - postgres
      - mailhog
      - rabbitmq
      - redis
    volumes:
      - ./src/Server:/app
    env_file:
      - ./.env/production/.django
    ports:
      - 8000:8000
    command: /start

  denselightnuxt:
    build:
      context: .
      dockerfile: ./compose/production/nuxt/Dockerfile
    container_name: denselight_nuxt
    env_file:
      - ./.env/production/.nuxt
    volumes:
      - ./src/Client:/app
    ports:
      - 3000:3000
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: shopit_nginx_image
    container_name: denselight_nginx
    ports:
      - 80:80
      - 443:443
      - 8001:8001
    depends_on:
      - denselightdjango
      - denselightnuxt

  redis:
    image: redis:5.0
    ports:
      - 6379:6379



#  celeryworker:
#    <<: *denselightdjango
#    image: denselightdjango_celeryworker
#    container_name: denselight_django_celery_worker
#    command: /start-celeryworker
#
#    env_file:
#      - ./env/production/.celeryworker
#
#    depends_on:
#      - denselightdjango

#  celerybeat:
#    <<: *denselightdjango
#    image: denselightdjango_celerybeat
#    container_name: denselight_django_celery_beat
#    command: /start-celerybeat
#
#    env_file:
#      - ./env/production/.celerybeat
#
#    depends_on:
#      - denselightdjango

#  flower:
#    <<: *denselightdjango
#    image: denselightdjango_flower
#    container_name: denselight_django_flower_beat
#    command: /start-flower
#
#    env_file:
#      - ./env/production/.celeryflower
#
#    depends_on:
#      - denselightdjango
