version: '3'

volumes:
  rabbitmqmain:
  rabbitmqdata:
  rabbitmqlogs:
  pgdata:


services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqmain:/etc/rabbitmq/
      - rabbitmqdata:/var/lib/rabbitmq/
      - rabbitmqlogs:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: denselight
      RABBITMQ_DEFAULT_PASS: denselight
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: denselight
      POSTGRES_DB: denselight_db
      POSTGRES_USER: denselight
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025

  denselightdjango: &denselightdjango
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    image: denselight_dev_django_image
    container_name: denselight_django
    depends_on:
      - postgres
      - mailhog
      - rabbitmq
      - redis
    volumes:
      - ./src/Server:/app
    env_file:
      - ./.env/development/.django
    ports:
      - 8000:8000
    command: /start

  denselightnuxt:
    build:
      context: .
      dockerfile: ./compose/development/nuxt/Dockerfile
    container_name: denselight_nuxt
    volumes:
      - ./src/Client:/app
    env_file:
      - ./.env/development/.nuxt
    ports:
      - 3000:3000
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/development/nginx/Dockerfile
    image: denselight_nginx_image
    container_name: denselight_nginx
    ports:
      - 80:80
      - 443:443
      - 8001:8001

    depends_on:
      - denselightdjango
      - denselightnuxt

  redis:
    image: redis:5.0

  celeryworker:
    image: denselight_dev_django_image
    command: /start-celeryworker
    container_name: denselight_django_celery_worker
    volumes:
      - ./src/Server:/app
    env_file:
      - ./.env/development/.celeryworker
      - ./.env/development/.django

    depends_on:
      - denselightdjango

  celerybeat:
    image: denselight_dev_django_image
    command: /start-celerybeat
    container_name: denselight_django_celery_beat
    volumes:
      - ./src/Server:/app
    env_file:
      - ./.env/development/.celerybeat
      - ./.env/development/.django

    depends_on:
      - denselightdjango


