# Generated by Django 3.1.2 on 2020-12-19 19:24
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Ticketing", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticket_Comments",
            new_name="TicketComments",
        ),
    ]
