# Generated by Django 3.1.2 on 2020-12-19 17:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overall_Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('goal_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competency_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skill_weightage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('goals_setting_end_date', models.DateField(default=datetime.date.today)),
                ('mid_year_start_date', models.DateField(default=datetime.date.today)),
                ('mid_year_end_date', models.DateField(default=datetime.date.today)),
                ('end_year_start_date', models.DateField(default=datetime.date.today)),
                ('appraisal_end_date', models.DateField(default=datetime.date.today)),
                ('reports_end_date', models.DateField(default=datetime.date.today)),
                ('calibration_end_date', models.DateField(default=datetime.date.today)),
                ('rating_scale', models.CharField(choices=[('Denselight System', 'Denselight System'), ('MiRXes', 'MiRXes')], default='Denselight System', max_length=50, null=True)),
                ('status', models.CharField(choices=[('Stage 1', 'Goals Setting'), ('Stage 1B', 'Mid-Year Review'), ('Stage 2', 'Year-End Review'), ('Stage 3', 'Reports'), ('Stage 4', 'Calibration'), ('Completed', 'Completed')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peerAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('strength1', models.CharField(blank=True, max_length=3000, null=True)),
                ('weaknessdevelopment1', models.CharField(blank=True, max_length=3000, null=True)),
                ('title2', models.CharField(default='NIL', max_length=200)),
                ('strength2', models.CharField(blank=True, max_length=3000, null=True)),
                ('weaknessdevelopment2', models.CharField(blank=True, max_length=3000, null=True)),
                ('title3', models.CharField(default='NIL', max_length=200)),
                ('strength3', models.CharField(blank=True, max_length=3000, null=True)),
                ('weaknessdevelopment3', models.CharField(blank=True, max_length=3000, null=True)),
                ('completion', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peerAppraisalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('completed', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('limiter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Appraisal_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('S1BEmployee', 'S1BEmployee'), ('S1BManager', 'S1BManager'), ('S1BReview', 'S1BReview'), ('S2Employee', 'S2Employee'), ('S2Manager', 'S2Manager'), ('Approved', 'Approved')], max_length=30)),
                ('appraisal_name', models.CharField(max_length=50, null=True)),
                ('overall_board_comments', models.CharField(blank=True, default='No Comments', max_length=5000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('completion', models.CharField(choices=[('null', 'null'), ('ECompleted', 'ECompleted'), ('MCompleted', 'MCompleted'), ('BCompleted', 'BCompleted'), ('Review', 'Review'), ('ReviewCompleted', 'ReviewCompleted')], default='null', max_length=50, null=True)),
                ('goals_settingM_rejection', models.CharField(default='NIL', max_length=3000)),
                ('mid_yearM_rejection', models.CharField(default='NIL', max_length=3000)),
                ('appraisalHR_rejection', models.CharField(default='NIL', max_length=3000)),
                ('mid_year_completion', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=15)),
                ('incrementRecommendation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bonusRecommendation', models.CharField(default='NIL', max_length=1000)),
                ('recommendationComments', models.CharField(default='NIL', max_length=1000)),
                ('final_employee_rating', models.IntegerField(blank=True, null=True)),
                ('final_manager_rating', models.IntegerField(blank=True, null=True)),
                ('final_board_rating', models.IntegerField(blank=True, null=True)),
                ('appraisal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.appraisal_category')),
            ],
        ),
    ]
