# Generated by Django 3.1.2 on 2020-12-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='user_appraisal_list',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='user_appraisal_list',
            name='overall_appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.overall_appraisal'),
        ),
        migrations.AddField(
            model_name='peerappraisalquestion',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.peerappraisal'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.user_appraisal_list'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorPA', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersPA', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='peerappraisal',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='overall_appraisal',
            name='appraisal_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.appraisal_category'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorA', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.user_appraisal_list'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersA', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.rating_scale'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userA', to='Profile.profile'),
        ),
    ]
