# Generated by Django 3.1.2 on 2021-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0002_auto_20201219_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='end_yearM_rejection',
            field=models.CharField(default='NIL', max_length=3000),
        ),
    ]
