# Generated by Django 3.1.2 on 2021-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0003_user_appraisal_list_end_yearm_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='completion',
            field=models.CharField(choices=[('null', 'null'), ('Ecompleted', 'Ecompleted'), ('MCompleted', 'MCompleted'), ('BCompleted', 'BCompleted'), ('Review', 'Review'), ('ReviewCompleted', 'ReviewCompleted')], default='null', max_length=50, null=True),
        ),
    ]
