# Generated by Django 3.1.2 on 2021-02-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0004_auto_20210203_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_appraisal',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
