# Generated by Django 3.1.2 on 2021-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0005_overall_appraisal_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overall_appraisal',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='user_appraisal_list',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
