# Generated by Django 3.1.2 on 2021-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0007_user_appraisal_list_end_year_employee_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='board_comments',
            field=models.CharField(default='NIL', max_length=2000),
        ),
        migrations.AddField(
            model_name='user_appraisal_list',
            name='board_rating',
            field=models.IntegerField(choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1),
        ),
    ]
