# Generated by Django 3.1.2 on 2021-03-09 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_auto_20210309_2234'),
        ('Appraisals', '0008_auto_20210309_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorA', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='employee_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.user_appraisal_list'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersA', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='rating_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.rating_scale'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userA', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='appraisal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.appraisal_category'),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='competency_weightage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='goal_weightage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='rating_scale',
            field=models.CharField(blank=True, choices=[('Denselight System', 'Denselight System'), ('MiRXes', 'MiRXes')], default='Denselight System', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='skill_weightage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='overall_appraisal',
            name='status',
            field=models.CharField(blank=True, choices=[('Stage 1', 'Goals Setting'), ('Stage 1B', 'Mid-Year Review'), ('Stage 2', 'Year-End Review'), ('Stage 3', 'Reports'), ('Stage 4', 'Calibration'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.user_appraisal_list'),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='completion',
            field=models.CharField(blank=True, choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managersPA', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title2',
            field=models.CharField(blank=True, default='NIL', max_length=200),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title3',
            field=models.CharField(blank=True, default='NIL', max_length=200),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='peerappraisalquestion',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.peerappraisal'),
        ),
        migrations.AlterField(
            model_name='peerappraisalquestion',
            name='completed',
            field=models.CharField(blank=True, choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rating_scale',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='rating_scale',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='appraisalHR_rejection',
            field=models.CharField(blank=True, default='NIL', max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='appraisal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appraisals.appraisal_category'),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='appraisal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='board_comments',
            field=models.CharField(blank=True, default='NIL', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='board_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='bonusRecommendation',
            field=models.CharField(blank=True, default='NIL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='completion',
            field=models.CharField(blank=True, choices=[('null', 'null'), ('Ecompleted', 'Ecompleted'), ('MCompleted', 'MCompleted'), ('BCompleted', 'BCompleted'), ('Review', 'Review'), ('ReviewCompleted', 'ReviewCompleted')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='end_yearM_rejection',
            field=models.CharField(blank=True, default='NIL', max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='goals_settingM_rejection',
            field=models.CharField(blank=True, default='NIL', max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='incrementRecommendation',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='mid_yearM_rejection',
            field=models.CharField(blank=True, default='NIL', max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='mid_year_completion',
            field=models.CharField(blank=True, choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=15),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='overall_appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appraisals.overall_appraisal'),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='recommendationComments',
            field=models.CharField(blank=True, default='NIL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='status',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('S1BEmployee', 'S1BEmployee'), ('S1BManager', 'S1BManager'), ('S1BReview', 'S1BReview'), ('S2Employee', 'S2Employee'), ('S2Manager', 'S2Manager'), ('Approved', 'Approved')], max_length=30),
        ),
    ]
