# Generated by Django 3.1.2 on 2021-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0009_auto_20210309_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appraisal_list',
            name='career_aspiration_employee',
            field=models.CharField(blank=True, default='NIL', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user_appraisal_list',
            name='career_aspiration_manager',
            field=models.CharField(blank=True, default='NIL', max_length=2000, null=True),
        ),
    ]
