# Generated by Django 3.1.2 on 2021-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0010_auto_20210328_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_appraisal_list',
            name='board_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], null=True),
        ),
    ]
