# Generated by Django 3.1.2 on 2020-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmation",
            name="token",
            field=models.CharField(
                default="E948-mn0QL5FhY3KsHfkXkWSGWWfdnF4v3OwyD_tF48",
                editable=False,
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="url_token",
            field=models.CharField(
                default="jn474dJ-JTOIrTxVOgW7EazzSTBxTz7AGLwggnJYJ_4",
                editable=False,
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HRManager", "HRManager"),
                    ("HR", "HR"),
                    ("Manager", "Manager"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=20,
                null=True,
            ),
        ),
    ]
