# Generated by Django 3.1.2 on 2020-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201223_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='second_Reporting_Manager',
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='nM1faTszKf0y8oYfVZMn5NAstLgIXNBggJ3rU9AnM14', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='I7r6QXbgUalE_Q-6FnlnVNsHrZTY8FOuB0F25VReXBo', editable=False, max_length=250),
        ),
    ]
