# Generated by Django 3.1.2 on 2020-12-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20201223_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='second_Reporting_Manager_Link',
            new_name='second_Reporting_Manager',
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='O5z2FaJbgHgG5z5K4GHUALJEElkv_crU1LGUVXpVFZE', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='HxLtZIAr42-zUW9rpueKNTNLVau2dTyPv_v3Dug0y1Q', editable=False, max_length=250),
        ),
    ]
