# Generated by Django 3.1.2 on 2020-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20201223_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='TvsN0LSw_ll1bwPek1vfytLLkQwaECMpLqL6DYpEiy8', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='N0dLyd1PRJxojxfXvtX86rJcQObS7Si0sGjBItKAGsc', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HRManager', 'HRManager'), ('Hr', 'Hr'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20, null=True),
        ),
    ]
