# Generated by Django 3.1.2 on 2020-12-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20201227_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='JzwKpAFxYhJXZxY12GyRxMm73fj82_4H1wTib8b5rEk', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='PYX2-lYZUpdIac9h5C9IPFssq6w-uC3IgXSO6vj99H0', editable=False, max_length=250),
        ),
    ]
