# Generated by Django 3.1.2 on 2021-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20201231_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='MWUzAxcJL9Ofo8saOzPAk4NpDaCwNTwlrOkp3aPNkuc', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='DhENbGe09TihPqrNhVMXDcJUaSVTNWJBpGCxVPhYUtg', editable=False, max_length=250),
        ),
    ]
