# Generated by Django 3.1.2 on 2021-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20210105_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='eBb80xJnq-BlZ22yQoBBE74fUFKsa7vmkVPLXezw4zs', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'info'), ('error', 'error'), ('success', 'success')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='jUxN0bdnC6h6Jc3hkgpdfbwoTYKk0b3I4k-VeNoQMFU', editable=False, max_length=250),
        ),
    ]
