# Generated by Django 3.1.2 on 2021-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20210105_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='mjcfLUobbma7zmdjsnqT5CfxamDhJFTyyR69cEMbwVI', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='u7PhQdqZeKE5XA7v1KsbO_rainMVCXp3QVXUOqDqIQk', editable=False, max_length=250),
        ),
    ]
