# Generated by Django 3.1.2 on 2021-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20210106_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='y4eyVGXqfXqi9ihxjFGioNrRbNPFQaFJLsVaB8yBxD8', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='YlT27w3CR_rKzLQVZSTg98KECxhmAUEFeBhStzrjwKc', editable=False, max_length=250),
        ),
    ]
