# Generated by Django 3.1.2 on 2021-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_auto_20210107_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='XooLcsIA5IdTmwtHK83sLPO6Yn766eW827sjGR7Hkhg', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='ElgExwl1nWlvfarmpHUxaVwnGZO43JE5pq12na8KWNo', editable=False, max_length=250),
        ),
    ]
