# Generated by Django 3.1.2 on 2021-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_auto_20210107_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='guide/thumbnail')),
                ('video', models.FileField(blank=True, null=True, upload_to='guide/video')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='xn4N5MAJs1CgjlrKZrs1W38OayMvD3uwq-v0_F1vKPQ', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='kSFL6td6qbBtAtHX2qkfM4w2hGwqUmPXzu8S-9-MkUw', editable=False, max_length=250),
        ),
    ]
