# Generated by Django 3.1.2 on 2021-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_auto_20210124_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_Of_Hire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_ID',
            field=models.CharField(default='S123456D', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeOfEmployee',
            field=models.CharField(choices=[('DIRECT', 'DIRECT'), ('INDIRECT', 'INDIRECT')], default='DIRECT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HRManager', 'HRManager'), ('Hr', 'Hr'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=20, null=True),
        ),
    ]
