# Generated by Django 3.1.2 on 2021-02-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_auto_20210203_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resign_date',
            field=models.DateTimeField(null=True),
        ),
    ]
