# Generated by Django 3.1.2 on 2021-03-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_auto_20210204_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship_Status',
            field=models.CharField(blank=True, default='-', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_Of_Hire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.departments'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_ID',
            field=models.CharField(blank=True, default='S123456D', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nric',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeOfEmployee',
            field=models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('INDIRECT', 'INDIRECT')], default='DIRECT', max_length=50, null=True),
        ),
    ]
